<?php
/**
 * Created by PhpStorm.
 * User: RedSun
 * Date: 2017/8/18
 * Time: 10:45
 */
namespace backend\Modules\roles\controllers\Base;

use yii\web\Controller;

class BaseController extends  Controller{
    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @param $key
     * @param string $default
     * @return array|mixed  统一获取psst参数的方法
     */
    public function post($key,$default = ''){
        return \Yii::$app->request->post($key,$default);
    }

    /**
     * @param $key
     * @param string $default
     * @return array|mixed  统一获取get参数的方法
     */
    public function get($key,$default = ''){
        return \Yii::$app->request->get($key,$default);
    }

    /**
     * @param array $data 数据区
     * @param string $msg 提示消息
     * @param int $code 状态码 200 表示成功
     * @throws \yii\base\ExitException  封装json返回值，主要用于ajax和后端交互 返回格式
     */
    public function renderJSON($data=[],$msg='ok',$code=200){
        header('Content-type:application/json');
        echo json_encode([
            'code' => $code,
            'msg' => $msg,
            'data' =>  $data,
            'req_id' => uniqid(),
        ]);
        return \Yii::$app->end();//终止请求直接返回
    }
}