<?php
/**
 * @Copyright Copyright (c) 2016 @Sms.php By Kami
 * @License http://www.yuzhai.tv/
 */

namespace common\ykocomposer\components;

use Yii;
use yii\base\Component;
use yii\log\Logger;
use common\ykocomposer\components\BaseSms;

/**
 * Class Sms
 * @package common\ykocomposer\components
 * @author  Yesela <yesela@163.com>
 */
class Sms extends Component
{

    /**
     * @var null 设置默认网关
     */
    public $defaultSP = null;

    public $SP = [];

    private $_SP =[];

    public $lastErrorMessage;

    /**
     * 创建SP
     * @throws \yii\base\InvalidConfigException
     */
    public function init()
    {
        foreach ($this->SP as $name => $config) {
            $config['class'] = "common\\ykocomposer\\components\\SP\\{$name}";
            $this->_SP[$name] = Yii::createObject($config);
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function send(array $content, $SP = null)
    {
        $this->defaultSP = $SP ? $SP : $this->defaultSP;
        $this->getSP()->lastErrorMessage = null;
        $result = $this->getSP()
                        //->initialize()
                        ->sendSMS($content);
                        /*->contentTransform()
                        ->replaceSignature()*/

        Yii::info('send SMS ', 'sms');
        return $result;
    }

    public function getLastErrorMsg()
    {
        return $this->getSP()->lastErrorMessage;
    }

    private function getSP()
    {
        return $this->_SP[$this->defaultSP];
    }
}