<?php
/**
 * @Copyright Copyright (c) 2016 @user.php By Kami
 * @License http://www.yuzhai.tv/
 */

/**
 * School translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Schools' => '学校',
    'School Setting' => '学校设置',
    'School List' => '学校列表',
    'All schools' => '所有学校',
    'Create School' => '创建学校',
    'View School' => '查看学校',
    'Name' => '名称',
    'Province ID' => '省份',
    'City ID' => '城市',
    'Area ID' => '区域',
    'District' => '区域',
    'Address' => '地址',
    'School Name' => '学校名称',
    'School Type' => '学校类型',
    'School Num' => '学校编号',
    'Manage Uid' => '管理员ID',
    'Quantong ID' => '全通ID',
    'Number' => '信息机编码',
    'Deny Code' => '禁止的编码',
    'Number1' => '信息机编码, 格式如: 名称1:编号1|名称2:编号2',
    'Deny Code1' => '禁止的编码, 格式如: 名称1:编号1|名称2:编号2',
    'Preschool' => '学前班',
    'Primary school' => '小学',
    'Junior high school' => '初中',
    'Senior middle school' => '高中',
    'Create' => '创建',
    'District Setting' => '区域设置',
    'Set District' => '设置区域选项',
    'Update' => '更新',
    'Delete' => '删除',
    'Update {modelClass}: ' => '更新学校: ',
    '{0, date, MMMM dd, YYYY HH:mm}' => '{0, date, dd MMMM, YYYY HH:mm}',
    'Are you sure you want to delete this item?' => '你确定要删除这条记录?',
    'Search' => '搜索',
    'Reset' => '重置',
    'Create' => '创建',
    'School Grade' => '年级',
    'School Grade List' => '年级列表',
    'Create Grade' => '创建年级',
    'Create School Grade' => '创建年级',
    'School Grades' => '年级列表',
    'School Area ID' => '区域ID',
    'School ID' => '学校ID',
    'Dateline' => '创建时间',
    'Display Order' => '排序',
    'Please Select {type}' => '--请选择{type}--',

    'Grade Setting' => '班级设置',
    'Grade List' => '班级列表',
    'Create Grade' => '创建班级',
    'All Grades' => '所有班级',

    'Grade' => '年级',
    'Room' => '班级',
    'Update Grade:' => '修改班级:',
];
